# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5bef450affedee2a0e43972660953bfe"
name = "Product Review"
handle = "product-review-129"
application_url = "https://campus-scheduled-translate-hidden.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://campus-scheduled-translate-hidden.trycloudflare.com/auth/callback",
  "https://campus-scheduled-translate-hidden.trycloudflare.com/auth/shopify/callback",
  "https://campus-scheduled-translate-hidden.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
